### PR TITLE
Create the generator

### PR DESCRIPTION
**Pull request by m-mujica**
I have to add more tests, but I have some questions:

a) **About the badge**, currently the generator asks the user to type the repository full name.... The issue mentions asking for the username instead (and try to retrieve it from the git remote) .... I noticed testing that since the repo has not been pushed to github (people following the guide) there won't be any git data to retrieve the user from. We could:

  1) Just remove the badge feature thing which simplifies a lot the code
  2) Maybe try to retrieve the github username by getting the email from the git config and then using something like this https://github.com/sindresorhus/github-username (the app name we get from the package json)
    2.1) the prompt would ask for each thing individually, instead of a single question like now.

a.1) I noticed that prepending the badge to the README causes yeoman to trigger the conflict resolution prompt, are we ok with this? 

a.2) is the warning ok when we can't find README.md, as opposed to aborting the whole thing like when `.travis.yml` is found?
            
b) We could **throw an error if `travis.yml` exists already**, but not sure if it's a good idea, I made it so a flag `this.abort` and the other methods in the generator just return early. Do we have a preferred approach here?

### CODE REVIEW

**Comment by matthewp** [comment]
> I noticed testing that since the repo has not been pushed to github (people following the guide) there won't be any git data to retrieve the user from.

I don't follow here, I think. In the guide you do add the remote before setting up travis. You don't *push* yet, but that should be ok I think. Can't you do `git remote get-url origin` and then parse out the user/repo from that?

a.1) Yeah, I think that's ok. Although there might be a way to prevent the prompt (I feel like one of our other generators does this but I'm not sure which).

a.2) Yeah, warning works here, the `.travis.yml` is the more important part.

b) Return early sounds ok here. I think we are more focused on the guide flow, where a .travis.yml won't exist yet, so handling other cases with early returns sounds ok.

**Comment by m-mujica** [comment]
> I don't follow here, I think. In the guide you do add the remote before setting up travis. You don't push yet, but that should be ok I think. Can't you do git remote get-url origin and then parse out the user/repo from that?

My bad, I did not check the guide in detail 😓 

I'm indeed getting the remote-url [here](https://github.com/donejs/donejs-travis/pull/3/files#diff-4c369dba87d04d9dd75de0ae4b320c64R45) but my local app does not have a remote and it fails... Ok, so even if we get the owner and the package name from the remote, we still want to prompt the user to type both and provide the values we parsed as the default right? like

- What's the github owner name ([value parsed])?
- what's the application name ([value parsed])?

So, if the remote was added the UX is cool, but what about someone trying out the command without a remote, should have dummy defaults in the questions?  like: 

- What's the github owner name (donejs)?
- what's the application name (my-app)?

or just no defaults at all?

**Comment by matthewp** [comment]
I think no defaults at all.

**Comment by m-mujica** [comment]
@matthewp this is ready for review:

screen shot 2018-02-08 at 1 38 57 pm

**Comment by matthewp** [comment]
Looks good!

**Pull request merged**
